### ISSUE TITLE
Link to previous lesson not working

### ISSUE THREAD

**Issue by Majd223** [microsoft/Data-Science-For-Beginners#127]
**Describe the bug**
A link that is supposed to take to the previous lesson is leading to a 404 error page.

**To Reproduce**
1. Go to '2-Working-With-Data'
2. Go to '06-non-relational'
3. Go to 'README.md'
4. Scroll to 'Document Data Stores with the Azure Cosmos DB'
5.  Click on the link saying 'previous lesson'

**Expected behavior**
The link should take to a previous lesson.

**Screenshots**
<img width="1106" alt="Screenshot 2021-09-28 133050" src="https://user-images.githubusercontent.com/76471403/135161261-bca6c4ba-f6d6-451a-aa10-a3a9a3cc7c39.png">

**Comment by jlooper** [comment]
fixed
