### ISSUE TITLE
Some Images are not showing in Deployment

### ISSUE THREAD

**Issue by anupamishra333** [microsoft/Data-Science-For-Beginners#129]

**Comment by jlooper** [comment]
Please be descriptive and show the links to broken images; note that I also just rearranged some images, so closing this for now

**Comment by anupamishra333** [comment]
![Screenshot (343)](https://user-images.githubusercontent.com/66557767/135320620-6e92943c-e53e-4b7e-a8c4-b8a795076d12.png)
Lesson 1 : introduction -> 04 stats and probability

**Comment by jlooper** [comment]
got it, thanks
