### ISSUE TITLE
VIDEO Intro to statistics. Shows "Height", but "Weight" is meant

### ISSUE THREAD

**Issue by bromero26** [microsoft/Data-Science-For-Beginners#154]
**Describe the bug**
At 2:32  and until 4:42 Dmitry mentions "Height" and a table showing baseball players heights is shown. Most likely Weight is meant. 

**Expected behavior**
The video should be edited again

**Screenshots**
![image](https://user-images.githubusercontent.com/40992230/135718688-5363074f-b0d3-4277-ba42-9467c335b04d.png)

**Comment by paladique** [comment]
Thanks for catching this, @bromero26! 

@shwars let us know what you'd like to do - I think an edit (adding a note/voiceover/background edit) would be fine

**Comment by purohitmansi** [comment]
Hello @paladique!

I am an openforce 2022 contributor. I would love to work on this issue and make PR as soon as I resolve the issue. Please do assign this to me.

ThankYou:)

**Comment by jlooper** [comment]
@purohitmansi we are not assigning issues in this repo and you won't be able to edit Dmitry's video.
