### ISSUE TITLE
Base README.md

### ISSUE THREAD

**Issue by maud-lv** [microsoft/Data-Science-For-Beginners#169]
Working on the French translation of the base README file

**Comment by bhumikatewary** [comment]
Hi, I am bhumikatewary, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you

**Comment by bhumikatewary** [comment]
I have made a PR:  Updated README.md #356
Please review and approve it
