### ISSUE TITLE
[TRANSLATIONS] Turkish

### ISSUE THREAD

**Issue by omerisildak** [microsoft/Data-Science-For-Beginners#247]
- [ ] Base README.md
- [ ] Quizzes
- [ ] Introduction base README
   - [ ] Defining Data Science README
   - [ ] Defining Data Science assignment
   - [ ] Ethics README
   - [ ] Ethics assignment
   - [ ] Defining Data README
   - [ ] Defining Data assignment
   - [ ] Stats and Probability README
   - [ ] Stats and Probability assignment
- [ ] Working with Data base README
   - [ ] Relational Databases README
   - [ ] Relational Databases assignment
   - [ ] Non-Relational Data README
   - [ ] Non-Relational Data assignment
   - [ ] Python README
   - [ ] Python assignment
   - [ ] Data Preparation README
   - [ ] Data Preparation assignment
- [ ] Vizualization base README
   - [ ] Quantities README
   - [ ] Quantities assignment
   - [ ] Distributions README
   - [ ] Distributions assignment
   - [ ] Proportions README
   - [ ] Proportions assignment
   - [ ] Relationships README
   - [ ] Relationships assignment
   - [ ] Meaningful Visualizations README
   - [ ] Meaningful Visualization assignment
- [ ] Data Science Lifecycle base README
   - [ ] Introduction README
   - [ ] Introduction assignment
   - [ ] Analyzing README
   - [ ] Analyzing assignment
   - [ ] Communication README
   - [ ] Communication assignment
- [ ] Data Science in the Cloud base README
   - [ ] Intro README
   - [ ] Intro assignment
   - [ ] Low Code README
   - [ ] Low Code  assignment
   - [ ] Azure README
   - [ ] Azure  assignment
- [ ] Data Science in the Wild base README
   - [ ] Real World Examples README
   - [ ] Real World Examples assignment

**Comment by omerisildak** [comment]
Can you assign it to me?

**Comment by TheDerebeyi** [comment]
Defining Data README kısmını halihazırda çevirdim daha fazla da katkı sağlayabilirim

**Comment by Kadermiyanyedi** [comment]
I am working on the  Working with Data base README - Python Readme sections. Please assign me to this section.

**Comment by Luarnight** [comment]
I am working on the Working with Introduction base README - Ethics assignment. Please assign me to this section.

**Comment by Sonerozcan** [comment]
I am working on the Data Preparation README. Please assign me to this section.

**Comment by jlooper** [comment]
closing for staleness
