### ISSUE TITLE
Mobile-friendly quizz-site

### ISSUE THREAD

**Issue by JULO01** [microsoft/Data-Science-For-Beginners#256]
As it is nice to do the lectures **on the way** (e.g. on the bus), 
it would be cool if the **quizz sites** of the lectures were **mobile friendly**.

A **redesign or some adaptions of the website** would be helpful, thank you. 😄 

![grafik](https://user-images.githubusercontent.com/90795588/140609360-b3edb815-52fe-4f9a-8d56-42a8dbd7bec3.png)

**Comment by jlooper** [comment]
Hi, you can access the lessons nicely on mobile using the site: https://microsoft.github.io/Data-Science-For-Beginners/#/1-Introduction/01-defining-data-science/README

for the quizzes, it looks like some changes to the navigation would be good on mobile, though it is still usable. Can you make a PR to fix?

**Comment by JULO01** [comment]
@jlooper 
Yes, I can do that. The source code for the quizz-app is on
[github.com/microsoft/Data-Science-For-Beginners/blob/main/quiz-app](https://github.com/microsoft/Data-Science-For-Beginners/blob/main/quiz-app)
right?
