### ISSUE TITLE
Visualization Lessons in R

### ISSUE THREAD

**Issue by paladique** [microsoft/Data-Science-For-Beginners#285]
Vidushi and Jasleen will be building out the R versions of the [Visualization Lessons](https://github.com/microsoft/Data-Science-For-Beginners/tree/main/3-Data-Visualization)

- [x]  Quantities 
- [x]  Distributions 
- [x]  Proportions 
- [x]  Relationships 
- [x]  Meaningful Visualizations

**Comment by jasleen101010** [comment]
Thanks @paladique!

**Comment by tandrimasingha** [comment]
Can you assign this issue to me. I'm a openforce'22 participant.

**Comment by Vidushi-Gupta** [comment]
Hi @tandrimasingha, this issue has already been worked upon! Please look for another issue which you would like to work on :)

**Comment by tandrimasingha** [comment]
Can I create my own issue? @Vidushi-Gupta

**Comment by jlooper** [comment]
@tandrimasingha in general we are not looking for minor changes or large enhancements to this curricula, but if you find a typo I will review and potentially merge.
