### ISSUE TITLE
The x and y labels in the PNG images are not readable when using a dark theme setting

### ISSUE THREAD

**Issue by flegaspi700** [microsoft/Data-Science-For-Beginners#298]
**Describe the bug**
The x and y labels in the PNG images in the link below are not readable when using a dark theme setting.
https://github.com/microsoft/Data-Science-For-Beginners/tree/main/3-Data-Visualization/09-visualization-quantities 

**To Reproduce**
View the page using a dark theme.
Go to profile -> Settings -> Appearance -> Select Dark Default or Dark Dimmed in Theme Preference -> Reload the Visualization Quantities page

**Expected behavior**
PNG images must be generated with "facecolor='white'", for the ONG images to be readable for both Light and Dark theme. 

**Screenshots**
Screenshot sample using Dark Dimmed setting.
![image](https://user-images.githubusercontent.com/75757416/142939126-f59e4707-d815-4e23-90d6-b046dbe01727.png)

I was able to test this in my repository using new PNG images.
https://github.com/flegaspi700/Data-Science-For-Beginners/tree/main/3-Data-Visualization/09-visualization-quantities

**Comment by jlooper** [comment]
If you'd like to create new images, please do so and PR. Please just do one PR for the entire fix, thanks!

**Comment by flegaspi700** [comment]
Done. I've created a PR.

**Comment by flegaspi700** [comment]
Closing this issue. PR has been created and merged.
