### ISSUE TITLE
Data Science In Buisness

### ISSUE THREAD

**Issue by anveshajain19** [microsoft/Data-Science-For-Beginners#355]
Using Data Science techniques to understand and analyze the large data sets available today has a huge impact on human lives.

I would like to add a readme so that everyone will understand the importance of Data Science in Business.

Data science tools enable organizations to analyze vast quantities of data from widely different sources and present that information in a way that allows data scientists to gain new knowledge, in some cases, saving hundreds of lives.

![Screenshot 2022-03-07 141901](https://user-images.githubusercontent.com/92093714/156998266-fbe37cc1-a770-4eaa-8be4-b095cf273c8c.png)

**Comment by jlooper** [comment]
hi, we are not looking to enhance this curriculum with this content as it is already covered. Thank you.
