### ISSUE TITLE
Probability challenge dataset is not available

### ISSUE THREAD

**Issue by NathanielPather** [microsoft/Data-Science-For-Beginners#380]
**Describe the bug**
Dataset for challenge is not available.

**To Reproduce**
1. Go to [/1-Introduction)/04-stats-and-probability/](https://github.com/microsoft/Data-Science-For-Beginners/blob/main/1-Introduction/04-stats-and-probability/notebook.ipynb)](https://github.com/microsoft/Data-Science-For-Beginners/blob/main/1-Introduction/04-stats-and-probability/notebook.ipynb)
2. Click on '[SOCR MLB Height/Weight Data](http://wiki.stat.ucla.edu/socr/index.php/SOCR_Data_MLB_HeightsWeights)'
3. See no download available for required dataset.

**Expected behavior**
Download link for dataset should be available.

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Chrome
 - Version 101.0.4951.67 (Official Build) (64-bit)

**Comment by jlooper** [comment]
hi, it's available on that web page as an embedded table, but maybe it should be exported with attribution

**Comment by NathanielPather** [comment]
> 

Thanks for your response, Jen.

What is attribution? I've tried googling and am only seeing results related to marketing. Could you clarify?

> Attribution refers to the set of rules that determine which ad gets credit for a sale or a conversion.

**Comment by jlooper** [comment]
hi @NathanielPather  - sorry, I wasn't clear. I meant that we can scrape the dataset from the page and link it, but I want to make sure to credit the original author, thus to give attribution so we don't lose sight of the source. thanks!
