### ISSUE TITLE
Quiz links are DEAD / Dead On Arrival... Please Squash these link bugs

### ISSUE THREAD

**Issue by richlysakowski** [microsoft/Data-Science-For-Beginners#413]
Links to pre-quizzes and post-quizzes are dead.  

No quizzes defeats the purpose of reinforcing "what is to be learned" and then "what was learned."

Dr. Rich Lysakowski

**Comment by leestott** [comment]
@richlysakowski  thanks for the heads up on this the web site will be up and running shortly apologies

**Comment by leestott** [comment]
@richlysakowski Websites are live apologies
