### ISSUE TITLE
2 translation files with the same content.

### ISSUE THREAD

**Issue by malialp** [microsoft/Data-Science-For-Beginners#495]
There are 2 translation files with the same content in the [translations](../tree/main/translations) folder.

- [README.ne.md](../tree/main/translations/README.ne.md)
- [README.ne.MD](../tree/main/translations/README.ne.MD)

It also causes this error to occur when cloning the repository.

![error](https://github.com/microsoft/Data-Science-For-Beginners/assets/109222729/072e2b7a-9642-44a7-beb1-3c8dbe0d2254)

**Comment by paladique** [comment]
@malialp thanks for highlighting this!

**Comment by guibracco** [comment]
This issue was closed, but the duplicated file was never removed and is still breaking git on cloned repos.

I've written the [PR #552](https://github.com/microsoft/Data-Science-For-Beginners/pull/552) removing the duplicated file from GitHub (and nothing more) in hopes that it helps.
