### ISSUE TITLE
Notebook Link Working on GitHub ReadMe.md but not in GitHub Pages

### ISSUE THREAD

**Issue by anupamishra333** [microsoft/Data-Science-For-Beginners#99]
Notebook Link Working on GitHub ReadMe.md but not in GitHub Pages getting 404 Error
![Screenshot (334)](https://user-images.githubusercontent.com/66557767/133847119-f3d5a8af-5569-460b-b552-981e70b08486.png)
KIndly Check @jlooper @paladique

**Comment by jlooper** [comment]
Notebooks should be used directly in VS Code. Probably we can put a note about that in the README

**Comment by jlooper** [comment]
The docsify deployment is what's behind the scenes for GH Pages. I don't think notebooks will work at all with docsify. Closing this, and adding a note in the README.

**Comment by anupamishra333** [comment]
Ohh then it will not work.
Thanks
